NAME = avscale

HEADERS = avscale.h         \
          version.h         \

OBJS = avscale.o                                                        \
       utils.o                                                          \
